//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ADO.NET.Test_exercise
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long CustomerId { get; set; }
        public int CustomerTitleId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerOtherInitials { get; set; }
        public string CustomerLastName { get; set; }
        public long AddressId { get; set; }
        public string AccountNumber { get; set; }
        public int AccountTypeId { get; set; }
        public decimal CleareBalance { get; set; }
        public decimal UncleareBalance { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
