//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ADO.NET.Test_exercise
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionId { get; set; }
        public long CustomerId { get; set; }
        public int TransactionType { get; set; }
        public System.DateTime DateEntered { get; set; }
        public decimal Amount { get; set; }
        public string ReferenceDetails { get; set; }
        public string Notes { get; set; }
        public Nullable<long> RelatedShareId { get; set; }
        public long RelatedProductId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Share Share { get; set; }
    }
}
